apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx 
  namespace: flux-system 
spec:
  install:
    remediation: 
      retries: 3
  upgrade:
    remediation:
      retries: 3
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx 
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx 
        namespace: flux-system
      interval: 1m
  targetNamespace: staging