apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis 
  namespace: flux-system 
spec:
  interval: 5m
  chart:
    spec:
      chart: redis 
      sourceRef:
        kind: HelmRepository
        name: redis 
        namespace: flux-system
      interval: 1m
  targetNamespace: staging